[package]
name = "ergodox_stand"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
nalgebra = "0.33.2"
once_cell = "1.19.0"
ordered-float = "4.2.2"
rand = "0.8.5"
scadman = { git = "https://github.com/lum1narie/scadman.git", tag = "v0.1.1", version = "0.1.0" }
